export const termsContent = `<html><body>

<h1>General Terms & Conditions</h1>
<h3>1. Service</h3>
<ol><li>1.1 The service of Aexol Demo Shop (hereafter referred to as "Service") is provided by Aexol Sp. z o.o., a Company incorporated under Polish law, with its registered office in Bialystok at Mlawska 4/U7 street, postal code: 15-411, NIP (EU VAT/Tax Identification no.) PL5423253283, registered in the National Court Register (KRS) by the District Court in Bialystok, XII Commercial Division of the National Court Register under KRS number 0000602817, with a share capital of PLN 5000 (hereafter referred to as "Company").</li> 
<li>1.2 In order to use the Service, you must first agree to the Terms & Conditions and Privacy Policy. You can agree to these regulations by using the appropriate check box. Using the Service assumes acceptance of the Terms & Conditions and Privacy Policy.</li> 
<li>1.3 You may not use the Service if you are a person barred from receiving the Service under Polish law or the laws of other countries, including the country in which you are resident or from which you use the Service. The Service may not be used by children and by using it you are confirming that you are over the age of 18.</li> 
<li>1.4 By using the Service you agree that its purchase is not contingent on the delivery of any future functionality or feature, or dependent on any oral or written public comments made by the Company or any of its affiliates regarding future functionalities or features.</li> 
<li>1.5 The Service is ordered by the Company's client (hereafter referred to as "Client") by sending the electronic form available at: <a href="https://shop.aexol.com/">https://shop.aexol.com/</a> (hereafter referred to as "Order"). The Company provides the Service for two types of Clients: Pro Plan Client (that is a individual Client), Enterprise Plan Client (that is a Company registered in the appropriate register)</li>
</ol>

<p>The Service made available to the Pro Plan Clients starts with a 14-day Pro trial, which is free. After the 14-day Pro trial expires, Service is made available to the Pro Plan Client after a payment in advance for the settlement period, which is either a month or a longer period of time if indicated so in the Company’s fees and payment policies at <a href="https://shop.aexol.com/">https://shop.aexol.com/</a> (hereafter referred to as "Settlement Period"​). The Company will issue an electronic bill to the Pro Plan Client, via Stripe, for all charges due in each Settlement Period. The Service will be available to the Pro Plan Client in each Settlement Period subject to payment of the Fee in advance. Service is made available to the Enterprise Client in a timetable agreed upon individually with persons authorized to represent the Enterprise Client.</p>
<span>More details can be found here: <a href="https://shop.aexol.com/">https://shop.aexol.com/</a></span>

<h3>2. Restricted Access to Services</h3>
<p>Should providing the Service result in a risk of more than insignificant damage to the Company, Clients of the Service or another entity, The Company may block or restrict access to the Service. In connection with this, the Company may not adopt more far-reaching measures than are justified in the circumstances. The Client shall be informed as soon as possible if the access to the Service is restricted. Unless otherwise stated in the service level guarantees, The Company may carry out planned measures that affect the availability of the Service if they are required for technical, maintenance, operational or safety reasons. The Company shall perform such measures promptly and in a manner that limits the disruption as much as possible.The Company undertakes to notify The Client within a reasonable time before such actions. The Company guarantees that The Service will be available fifty one percent (51% ) of the time in a given calendar month, except to the extent that (i) any Client provided hardware or software fails or is defective and said failure or defect causes, in whole or in part, the downtime, (ii) the Service is suspended (see ​ Section 7​) or (iii) as specified in these Terms (including in this ​Section 2​). Availability shall be measured at the exit (outbound port) of the firewall at The Company's data center. The Client's sole and exclusive remedy for any failure in providing the Service according to the foregoing guarantee is that the Company will provide the Service free of charge for the next settlement period. No other liabilities can be concluded from this statement.
</p>
<h3>3. Fees</h3>
<p>The current Service fees are listed on <a href="https://shop.aexol.com/">https://shop.aexol.com/</a> (hereafter referred to as "Fees"). The Fees can be changed once a year for the Client. The Company may change its fees and payment policies for the Service by notifying the Client at least fifteen (15) days before the beginning of the billing cycle in which such change will take effect. Changes to the fees or payment policies will be announced by being posted on the website (or some other URL <a href="https://shop.aexol.com/">https://shop.aexol.com/</a> may provide from time to time). Any outstanding balance becomes immediately due and payable upon termination of the Terms for any reason.
</p>
<h3>4. Payment</h3>
<ol>
<li>4.1. The Service Fee is paid in advance upon generating the electronic bill and on a monthly basis or at the interval indicated in The Company’s fees and payment policies in <a href="https://shop.aexol.com/">https://shop.aexol.com/</a>.</li>
<li> 4.2. The Company will charge the Client’s credit card on a monthly basis or at the interval indicated in the Company fees and payment policies in <a href="https://shop.aexol.com/">https://shop.aexol.com/</a>. Late payments may bear interest at the rate of annually 9 % above base interest rate (or the highest rate permitted by law, if less). The charges are tax exclusive. The Client is responsible for paying all taxes and government charges, and all reasonable expenses and attorneys fees the Company incurs by collecting late payments. To the fullest extent permitted by law, the Client waives all claims relating to charges unless claimed within 30 days after the charge (this does not affect your credit card issuer rights). Charges are solely based on the Order of the Company Services, unless otherwise agreed to in writing. To the fullest extent permitted by law, refunds (if any) are at the discretion of the Company and only in the form of credit for the Company’s Services. Nothing in these Terms obligates the Company to extend credit to any party. The Company reserves the right to discontinue providing the Service to the Client in the event of any late payments.
</li></ol>
<h3>5. Support</h3>
<p>Support is provided via e-mail ticketing system: support@aexol.com. The response time is usually within the next three business days (excluding statutory holidays in Poland) between 9 AM and 5 PM (CET) per ticket, although - it's guaranteed only in the "Dedicated" plan according to the Company's offer at <a href="https://shop.aexol.com/">https://shop.aexol.com/</a> (if available). Support provided by these Terms does not guarantee a timeframe for error repair. Support does not include services for customizing the Service - those are set individually by the Company and the Client on the basis of a separate agreement for an additional fee.
</p>
<h3>6. Backups</h3>
<p>Backups are stored for 7 (seven) days on a separate machine, made daily, restored in case of a service failure​. The subjects of Backups are code and database snapshots.
</p>
<h3>7. Term and termination</h3>
<p>Service can be terminated by both parties with a 7 (seven) days notice period coming into effect at the end of Settlement Period. The Company may terminate the Service immediately without the notice period in case of: 
</p>
<ol>
<li>(i) breach of these Terms by the Client</li>
<li>(ii) the Client publishing any content that's violating the law or is otherwise inappropriate</li>
<li>(iii) the Client’s failure to finally pay overdue bills within 7 (seven) days after the applicable due date. In the case of termination for the above mentioned reasons the Company will have no obligation to provide a refund of any amount previously paid by the Client or any damage incurred by the the Client or his partners (i.e. subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers). In case of a delay in payment for any due bills by the Client, the Company is entitled to suspend the provision of the Services, without notice, until the payment of delayed fees is made. Any such suspension will in no way relieve the Client from paying the fees. The Company is entitled to delete the account in the event the Client: fails to confirm the authenticity of the e-mail, has not used the services for 12 months, or at the Client's request.
</li>
<h3>8. Warranty</h3>
<p>The services are provided "as is". The Company does not provide a guarantee or a warranty for service. The Company makes no other warranties, express, implied or arising by custom or trade usage, and, specifically, makes no warranty of title, non-infringement, accuracy, quiet enjoyment, merchantability or fitness for any particular purpose. The Company's express warranties will not be enlarged, diminished or affected by, and no obligation or liability will arise out of, the Company rendering technical or other advice or service in connection with the software.
</p>
<h3>9. Liability</h3>
<p>
Under no circumstances will Aexol be liable for: loss of profits, revenue; loss of actual or anticipated profits; loss of contracts; loss of the use of money; actual damage, loss of anticipated savings; loss of business; loss of opportunity; loss any data, loss data after modification termination block or restrict access to the service, delete the account of Client, loss of job, loss of goodwill; loss of reputation; damage to or corruption of data, actions and damages connection with force majeure, loss anything by the Client after his actions or omissions, or consequential or indirect loss or special, punitive, or incidental damages (including, for the avoidance of doubt, where such loss or damage is also of a category of loss or damage already listed), whether foreseeable or unforeseeable, based on claims of Client, Company or any third party arising out of any breach or failure of express or implied warranty conditions or other term, breach of contract, misrepresentation, negligence, other liability in tort, failure of any remedy to achieve its essential purpose, or otherwise. under no circumstances will aexol be liable for mislead or our not culpable faults. Company will not be liable for any content provided or published or imported or exported by the Client or others faults made in another services which Company uses. notwithstanding the form (e.g.,contract, tort, or otherwise) in which any legal or equitable action may be brought. in no event will the Company or its suppliers be liable for damages, expenses, costs, liabilities, suits, claims, restitution or all another losses, that exceed, the (one) monthly services fee paid to the Company in the settlement period in which the event causing liability occurred. under no circumstances will the Company be liable for any errors that may occur while using any of the features:
Regardless of the basis of the claim (i.e. contractual and tort liability), the liability of the Company for damage with the Service in relation to a single damage may not exceed 10% of the of the last net monthly fee paid to the Company or 10% of the of the last net annual fee paid to the Company (if the Client chose this type of payment); the maximum liability of the Company may not exceed 100% of the net annual fees, regardless of the number and nature of the claims. The above limitation of liability shall not apply in the event of willful misconduct and any other liability cases whose contractual limitations are prohibited by law.
</p>
<h3>10. Intellectual property</h3>
<ol><li>10.1. These Terms do not transfer from the Company to the Client or any third party, the intellectual property, and all rights, titles and interest in and to such property will remain (as between the parties) solely with the Company. The Company logo, and all other trademarks, service marks, graphics and logos used in connection with the Services are trademarks or registered trademarks of the Company, or its licensors. Other trademarks, service marks, graphics and logos used in connection with the website may be the trademarks of other third parties. The Client's use of the Services grants to the Client no right or license to reproduce or otherwise use any Company or third-party trademarks or logos. Subject to that the Company may consent to the use of the Company's logo on the Client's website. Such consent must be explicit and given by persons authorized to represent the Company.</li><li> 10.2. Parties agree that, according to these Terms the realized business cooperation, the Company may use the Client's Company name without any fees as a reference on its official website, presentation, lecture, conference or other means of advertising and/or promoting its professional activities. In justified cases, the Company may also use the Client's Company logo. Parties agree that the Company may, as a reference, mention the Client and their mutual business operations in the course of negotiations, offers and/or similar types of business interactions with third parties.</li>
</ol>
<h3>11. Modification and Termination of the Services.</h3>
<ol><li>11.1 The Service is constantly advancing in order to provide the best possible experience for its users. The Client acknowledges and agrees that the form and nature of the Company’s Services which the Company provides may change from time to time without prior notice to the Client, subject to the Terms in Section 3. Changes to the form and nature of the Company’s Services will be effective with respect to all versions of the Services; examples of changes to the form and nature of the Services include without limitation, changes to fee and payment policies, security patches, added functionality and other enhancements. The Client may terminate these Terms at any time by canceling his account on the Services. The Client will not receive any refunds in the event of canceling his account. The Client agrees that the Company, in its sole discretion and for any or no reason, may terminate his account or any part thereof. The Client agrees that any termination of his access to the Service may be without prior notice, and agrees that the Company will not be liable to him or any third party for such termination and its consequences.</li> <li>11.2. The Client is solely responsible for exporting his content and application(s) from the Service prior to termination of his account for any reason. Upon any termination of the Service or his account these Terms will also terminate, but Sections 8, 9, 10, 11,12, 13, shall continue to be in effect after these Terms are terminated.
</li></ol>
<h3>12. Indemnification</h3>
<p>The Client agrees to hold harmless, defend and indemnify the Company, and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners (collectively "Company and Partners") from and against any third party claim arising from or in any way related to (a) the Client’s breach of the Terms, (b) the Client’s use or other activities of the Services, (c) the Client’s violation of applicable laws, rules or regulations in connection with the Services, or (d) the content or the Client’s application, including any liability or expense arising from all claims, losses, damages (actual and consequential and lost of profits), suits, judgments, litigation costs and attorneys' fees, of every kind and nature. In such cases, the Company will provide the Client with written notice of such claim, suit or action.
</p>
<h3>13. General</h3>
<ol><li>13.1. If any provision of these Terms is found by any court or administrative body of competent jurisdiction to be invalid, unenforceable or illegal, the other provisions shall remain in force. The Parties are independent contractors. These Terms will not be construed as constituting either Party as a partner of the other or to create any other form of legal association that would give one party the express or implied right, power or authority to create any duty or obligation of the other party.</li><li> 13.2. Governing Law and Jurisdiction. Agreement shall be governed by Polish law. Any disputes that may arise on the basis of the Agreement, will be settled by the Polish court in Warsaw.</li><li> 13.3. These Terms may change, in that case the Company will inform the Client about new Terms via a notification on his account. The Client will be entitled to withdraw the Service via e-mail within 14 days from that information.</li></ol></body</html>`;
